### ISSUE TITLE
MY Stream logic fixes

### ISSUE THREAD

**Issue by falon3** [CMPUT404Group/CMPUT404-project-socialdistribution#13]
So our 'my stream' should be including:

my posts
public posts of those that I follow
friends posts
friends of friends posts (or should this be: friends of friends_ public_ posts?)
NOT public posts from everywhere in the world

**Comment by falon3** [comment]
nevermind it's working now I guess

**Comment by vanbelle** [comment]
I did most of this on friday, what myStream shows:
my posts
friends posts that i am allowed to see
all the posts of the people i am following that i am allowed to see (ie if i am following someone and i am their foaf and the privacy setting is set to foaf then i see that.) 

NOTE: if a foaf posts something, but i am not following them, even if i am allowed to see it, it wont appear in the mystream.

I hope thats ok? let me know if that wasnt what you guys wanted, then i would change it.

**Comment by falon3** [comment]
Yup sorry Sarah I thought there was still confusion for how it worked for a moment there and why the "follow" button wasn't acting as expected. But yup turns out to be good I believe! 

although still haven't been abel to test if the friend things actually work yet unless make freinds directly from backend and see
