### ISSUE TITLE
User Stories: Friends

### ISSUE THREAD

**Issue by vanbelle** [CMPUT404Group/CMPUT404-project-socialdistribution#3]
- [x] As an author, I want to befriend local authors
- [x] As an author, I want to befriend remote authors
- [x] As an author, I want un-befriend local and remote authors
- [x] As an author, When I befriend someone it follows them, only when the other authors befriends me do I count as a real friend.
- [x] As an author, I want to know if I have friend requests.
- [x] As an author, my server will know about my friends

**Comment by jlx339** [comment]
1

**Comment by jlx339** [comment]
friend - all done
