### ISSUE TITLE
Fix displaynames

### ISSUE THREAD

**Issue by falon3** [CMPUT404Group/CMPUT404-project-socialdistribution#30]
displayname should just be same as username---> changed that username is shown when hovering not displayname, but couldn't get the model to be configured so that displayname from author is equal to username from user.

remote pictures should just be their username when hovered

**Comment by falon3** [comment]
I don't know how to change what the display is when mouse hovers over the picture of the post author our template only knows the remote author fields: id, host, github.... Why can't we get the other information from our remote authors of posts?

**Comment by falon3** [comment]
for remote authors of posts this doesn't work for some reason.... don't have option of username or display name in the template for remotes.? not sure why is done the same as mainstream regular ones are

**Comment by genevag** [comment]
I have this fixed, I just haven't pushed yet.

**Comment by falon3** [comment]
ohhh wicked thanks geneva
