### ISSUE TITLE
User Stories: Posting

### ISSUE THREAD

**Issue by vanbelle** [CMPUT404Group/CMPUT404-project-socialdistribution#4]
- [x] As an author I want to make posts.
- [x] As an author, posts I create can link to images.
- [x] As an author, posts I make can be in simple plain text
- [x] As an author, posts I make can be in markdown (commonMark is good)
- [x] As an author, I want to delete my own posts.
- [x] As an author, I want to comment on posts that I can access
- [x] As an author, I want to post posts to my “stream”
- [x] As an author, I want to pull in my github activity to my “stream”

**Comment by falon3** [comment]
github seems to work, but is in an ugly format
