### ISSUE TITLE
Option to follow myself on the myStream page. 

### ISSUE THREAD

**Issue by vanbelle** [CMPUT404Group/CMPUT404-project-socialdistribution#41]
Option to follow myself on the myStream page. 
Also people who I have followed, have the "follow" option on the mystream
The display name does not appear when we mouseover the image

**Comment by falon3** [comment]
doesn't the username appear now instead?? that's how it is on mine. Cuz I hated the defaultdisplayname thing so I changed it to username

oh except I can't get a single post to appear on myStream so I can't actually verify this there :S but other places it works

**Comment by falon3** [comment]
this is fixed right? sarah did you push?
