### ISSUE TITLE
User Stories: UI

### ISSUE THREAD

**Issue by vanbelle** [CMPUT404Group/CMPUT404-project-socialdistribution#5]
- [x] As a server admin, I want a restful interface for most operations

**Comment by cheng10** [comment]
Views we might need in this application: 
1. sign up page : 
   display a sign up form
2. my_stream : 
   display user's own past posts and user himself is able to delete/manage it
3. all_stream/homepage: 
   user is able to see all available posts as well as comment and search them.
   Also able to (un)follow(sent friend request) local/remote authors. 
   User can also send posts on this page. 
   (type: img_link(access protected), text, markdown, github, twitter etc.)
   (privilege: to me, to another author, to friends, to friends of friends, only to friends on my node, public )
4. firend_request_manage: 
   user is able to reply friend request sent to him
5. following stream: 
   user is able to see all public posts from local/remote authors he followed or friended
   able to comment/unfollow them.
6. my_profile: 
   user is able to edit his own profile
7. admin_homepage: 
   admin is able to add/remove/edit users. 
   able to see all the users in this node. 
   able to see all the authors' friends. 
   able to manage the signup waiting list. 
   able to auth and connect/disconnect to other nodes. (posts/images) 
8. user_profile:
   all registered users are able to see/comment one's public posts on one's homepage. 
   admins are able to see all of one's posts on one's homepage. 
9. my_friends:
   user is able to delete/manage his own friends on this page.
