### ISSUE TITLE
User Stories: Miscellaneous

### ISSUE THREAD

**Issue by vanbelle** [CMPUT404Group/CMPUT404-project-socialdistribution#8]
- [x] As a server admin, images can be hosted on my server.
- [x] As an author, I want a consistent identity per server
- [x] As an author, I want to be able to use my web-browser to manage my profile
- [x] As an author, I want to be able to use my web-browser to manage/author my posts
- [x] As a server admin, I don’t want to do heavy setup to get the posts of my author’s friends.
- [x] As an author, I want to feel safe about sharing images and posts with my friends – images should not publicly accessible without authentication.

**Comment by falon3** [comment]
haven't made a thing to get the images yet tho.... but they get uploaded and saved at least.

**Comment by cheng10** [comment]
In order to implement this user story: 
" As a server admin, I don’t want to do heavy setup to get the posts of my author’s friends."
I think we need to add a manager's page, not just the Django default /admin page.
