### ISSUE TITLE
Database Creation

### ISSUE THREAD

**Issue by vanbelle** [CMPUT404Group/CMPUT404-project-socialdistribution#9]
- [x] Make a mysql Database  
  Needed Database elements
  - [x] User
  - User name
  - Profile picture (optional)
  -  Friend List
  - Stream/post list
  - friend request list
  - id
  - login info
  - following list
  - location (server id)
  - [x] Posts
  - author
  - file type (markdown/plaintext/github file/etc)
  - privacy/privilege
  - date
  - content
  - image url
  - title/subject
  - id
  - tags?
  - comment list
  - [x] Comments *will inherit the privilege from the post
  - contents
  - author
  - image url
  - id
  - [x] Admin
  - id
  - login info
  - node id?
  - server list?
  - all posts list?
  - user list
  - wannabe user list
- [  ] Images ???? as stringss??

**Comment by cheng10** [comment]
draft database schema

users{
 userid PK,
 username,
 pwd,
 waiting_status;
 github_name;
}

posts{
 id PK,
 author_id FK users,
 title,
 type,
 privilege,
 pub_time,
 content,
 img_url,
 viewer, (optional)
}

admins{
 username PK,
 pwd,
 nodename FK nodes,
}

nodes{
 nodename PK,
 author_id FK users,
}

comments{
 id PK,
 author_id FK users,
 text,
 pub_time,
}

friending{
 userid PK FK users,
 friend_id PK FK users,
}

following{
 userid PK FK users,
 following_id PK FK users,
}

commenting{
 post_id PK FK posts,
 comment_id PK FK comments,
}

**Comment by falon3** [comment]
do we need tags or something in our posts? I'm not sure how twitter and hash tags work really

and what are nodes here?

Otherwise looks good so far to me

**Comment by cheng10** [comment]
We could take tags as optional, as it is not required in the spec. 
The node table basically records which server(node) authors are in. It will make things easier when it comes to admin adds/deletes authors from the server. Also, it may be a good schema since we need to connect to other servers later on.

**Comment by falon3** [comment]
has the one Post model that is in the post.models.py file been tested and can work to create objects right now using whatever database the default is with django? I'm not sure how to test it by creating objects from the terminal right now... I tried it in ipython or python environment but am unsure. It should work just like these instructions right?: https://docs.djangoproject.com/en/1.8/topics/db/models/

**Comment by cheng10** [comment]
Yes, I tried with the default /admin administration page, almost works well. There is a little bug though, we can fix that using custom admin page later on. Django uses (ORM)Object-relational mappers, it transfers of data stored in relational databases tables into objects that are more commonly used in application code. So, Django handled database part implicitly, reduced a lot workload of us.

**Comment by cheng10** [comment]
Are we still planning using MySQL instead of Postgres? The official document suggests that Postgres is the best choice. However, it is pretty easy to switch database though,  I am currently sticking to sqlite3 in development. 
https://docs.djangoproject.com/en/1.9/topics/migrations/

**Comment by falon3** [comment]
I personally like the way the documentation for django all supports the Postgres... and really even though we have experience with MySQL, we would have to reference most things anyways because it's been awhile I'm sure for our memories.... so maybe referencing something that is similar but well-documented within django for our use would make our lives easier
